code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension chadalen.vscode-jetbrains-icon-theme
code --install-extension cschlosser.doxdocgen
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension genieai.chatgpt-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension golf1052.code-sync
code --install-extension Hridoy.rails-snippets
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension mateocerquetella.xcode-12-theme
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension rebornix.ruby
code --install-extension sianglim.slim
code --install-extension twxs.cmake
code --install-extension wingrunr21.vscode-ruby
